name: Deploy

on:
  push:
    branches:
      - main


env:
  ENABLE_DEPLOY: false


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: CI/CD Disabled
      if: env.ENABLE_DEPLOY == 'false'
      run: |
        echo "CI/CD is temporarily disabled."
        echo "Deployment will be done manually."


    - name: Test host format
      if: env.ENABLE_DEPLOY == 'true'
      run: |
        if [[ "${{ secrets.SERVER_HOST }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "SERVER_HOST looks like an IP"
        else
          echo "SERVER_HOST format is wrong"
          exit 1
        fi


    - name: Test SSH Port
      if: env.ENABLE_DEPLOY == 'true'
      run: |
        timeout 10 bash -c "</dev/tcp/${{ secrets.SERVER_HOST }}/2222" \
        && echo "Port 22 open" \
        || echo "Port 22 closed"

        echo "Testing ping..."
        ping -c 4 ${{ secrets.SERVER_HOST }} || true

        echo "Testing nc..."
        nc -vz -w 5 ${{ secrets.SERVER_HOST }} 22


    - name: Deploy to Server
      if: env.ENABLE_DEPLOY == 'true'
      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.SERVER_HOST }}

        username: ${{ secrets.SERVER_USER }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        port: 22

        debug: true

        script: |

          cd ~/Thread-Proccess

          git pull

          docker build -t thread-process .

          docker stop thread-api || true

          docker rm thread-api || true

          docker run -d \
          --name thread-api \
          -p 8000:8000 \
          -v thread-data:/app/data \
          thread-process