name: Deploy

on:
  push:
    branches:
      - main


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Test SSH Port
      run: |
        ping -c 4 ${{ secrets.SERVER_HOST }}
        nc -vz -w 5 ${{ secrets.SERVER_HOST }} 22

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.SERVER_HOST }}

        username: ${{ secrets.SERVER_USER }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |

          cd ~/Thread-Proccess

          git pull

          docker build -t thread-process .

          docker stop thread-api || true

          docker rm thread-api || true

          docker run -d \
          --name thread-api \
          -p 8000:8000 \
          -v thread-data:/app/data \
          thread-process